# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: docker.io/satish736/mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: satish

  adminer:
    image: docker.io/satish736/abc:latest
    restart: always
    ports:
      - 8090:8090
